"use strict";

// COORD-150: tests for `coord init --wizard` — the config-as-code scaffolder.
// Never mutates the real repo's coord/ — every write test uses an os.tmpdir()
// scratch directory.
//
// Covers:
//   - the PURE generator: given answers -> expected project.config.js (the
//     generated config is deterministic + structurally valid);
//   - no-clobber/idempotent: re-run with same answers is a no-op; an existing,
//     differing config is NOT overwritten without --confirm (plan is shown);
//   - --dry-run writes nothing;
//   - the dispatcher wires `coord init --wizard` to the wizard.

const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");
const Module = require("node:module");

const createCoordInitWizard = require("./coord-init-wizard.js");
const { generateProjectConfig, normalizeAnswers } = require("./coord-init-wizard.js");
const createCoordInit = require("./coord-init.js");

function capture() {
  const lines = [];
  return { log: (line) => lines.push(String(line)), text: () => lines.join("\n") };
}
function tmpRoot() {
  return fs.mkdtempSync(path.join(os.tmpdir(), "coord-wizard-test-"));
}

const ANSWERS = {
  coordTicketPrefix: "ACME",
  repos: [
    { code: "B", path: "backend", integrationBranch: "main", testCommand: "npm run test:ci", ticketPrefixes: ["MSRV"] },
    { code: "F", path: "frontend", integrationBranch: "develop", ticketPrefixes: ["FE", "WEB"] },
  ],
};

// --- pure generator ----------------------------------------------------------

test("generateProjectConfig: answers -> expected, deterministic config-as-code", () => {
  const out1 = generateProjectConfig(ANSWERS);
  const out2 = generateProjectConfig(ANSWERS);
  assert.equal(out1, out2, "generator must be deterministic for the same answers");

  assert.match(out1, /coordTicketPrefix: "ACME"/);
  assert.match(out1, /B: \{/);
  assert.match(out1, /path: "backend"/);
  assert.match(out1, /integrationBranch: "develop"/);
  assert.match(out1, /ticketPrefixes: \["FE", "WEB"\]/);
  assert.match(out1, /testCommand: "npm run test:ci"/);
  // Defaulted testCommand for repo F (none supplied).
  assert.match(out1, /testCommand: "npm test"/);
  // GENERATED marker + config-as-code stance, never "live mutator".
  assert.match(out1, /GENERATED by `coord init --wizard`/);
});

test("generated config is a valid, requireable module with the right shape", () => {
  const src = generateProjectConfig(ANSWERS);
  const m = new Module("generated-config-test");
  m._compile(src, "generated-config-test.js");
  const cfg = m.exports;
  assert.equal(cfg.coordTicketPrefix, "ACME");
  assert.deepEqual(Object.keys(cfg.repos).sort(), ["B", "F"]);
  assert.equal(cfg.repos.B.path, "backend");
  assert.equal(cfg.repos.F.integrationBranch, "develop");
  assert.deepEqual(cfg.repos.B.ticketPrefixes, ["MSRV"]);
});

test("normalizeAnswers rejects reserved code X, bad codes, dupes, and empty repos", () => {
  assert.throws(() => normalizeAnswers({ repos: [] }), /at least one repo/);
  assert.throws(() => normalizeAnswers({ repos: [{ code: "X", path: "x" }] }), /reserved/);
  assert.throws(() => normalizeAnswers({ repos: [{ code: "BB", path: "x" }] }), /single uppercase/);
  assert.throws(
    () => normalizeAnswers({ repos: [{ code: "B", path: "a" }, { code: "B", path: "b" }] }),
    /duplicate/
  );
});

// --- no-clobber / idempotent / dry-run via run() -----------------------------

test("wizard creates config in a fresh dir from flags", () => {
  const root = tmpRoot();
  const cap = capture();
  const w = createCoordInitWizard({ log: cap.log, cwd: () => root });
  const result = w.run(["--non-interactive", "--dir", root, "--coord-prefix", "ACME", "--repo", "B:backend", "--repo", "F:frontend:develop"]);
  assert.equal(result.code, 0);
  assert.equal(result.action, "create");
  const cfgPath = path.join(root, "coord/project.config.js");
  assert.ok(fs.existsSync(cfgPath));
  const src = fs.readFileSync(cfgPath, "utf8");
  assert.match(src, /coordTicketPrefix: "ACME"/);
  assert.match(src, /integrationBranch: "develop"/);
  assert.match(cap.text(), /create  coord\/project\.config\.js/);
  assert.match(cap.text(), /config-as-code/);
  fs.rmSync(root, { recursive: true, force: true });
});

test("wizard is idempotent — re-run with same answers is a no-op skip", () => {
  const root = tmpRoot();
  const args = ["--non-interactive", "--dir", root, "--coord-prefix", "ACME", "--repo", "B:backend", "--repo", "F:frontend:develop"];
  createCoordInitWizard({ log: () => {}, cwd: () => root }).run(args);
  const cfgPath = path.join(root, "coord/project.config.js");
  const before = fs.readFileSync(cfgPath, "utf8");

  const cap = capture();
  const result = createCoordInitWizard({ log: cap.log, cwd: () => root }).run(args);
  assert.equal(result.code, 0);
  assert.equal(result.action, "skip");
  assert.match(cap.text(), /already matches the generated config|up to date/);
  assert.equal(fs.readFileSync(cfgPath, "utf8"), before, "no-op re-run must not change bytes");
  fs.rmSync(root, { recursive: true, force: true });
});

test("wizard is NO-CLOBBER — an existing, differing config is preserved without --confirm", () => {
  const root = tmpRoot();
  fs.mkdirSync(path.join(root, "coord"), { recursive: true });
  const cfgPath = path.join(root, "coord/project.config.js");
  const handEdited = "module.exports = { HAND_EDITED: true };\n";
  fs.writeFileSync(cfgPath, handEdited);

  const cap = capture();
  const result = createCoordInitWizard({ log: cap.log, cwd: () => root }).run([
    "--non-interactive", "--dir", root, "--repo", "B:backend",
  ]);
  assert.equal(result.code, 0);
  assert.equal(result.action, "skip");
  // Bytes preserved — no silent clobber.
  assert.equal(fs.readFileSync(cfgPath, "utf8"), handEdited);
  // But the plan/diff IS shown so the operator can decide.
  assert.match(cap.text(), /exists and differs|Proposed changes|--confirm/);
  fs.rmSync(root, { recursive: true, force: true });
});

test("wizard --confirm regenerates an existing, differing config", () => {
  const root = tmpRoot();
  fs.mkdirSync(path.join(root, "coord"), { recursive: true });
  const cfgPath = path.join(root, "coord/project.config.js");
  fs.writeFileSync(cfgPath, "module.exports = { OLD: true };\n");

  const result = createCoordInitWizard({ log: () => {}, cwd: () => root }).run([
    "--non-interactive", "--dir", root, "--coord-prefix", "ACME", "--repo", "B:backend", "--confirm",
  ]);
  assert.equal(result.code, 0);
  assert.equal(result.action, "update");
  assert.match(fs.readFileSync(cfgPath, "utf8"), /coordTicketPrefix: "ACME"/);
  fs.rmSync(root, { recursive: true, force: true });
});

test("wizard --dry-run writes nothing", () => {
  const root = tmpRoot();
  const cap = capture();
  const result = createCoordInitWizard({ log: cap.log, cwd: () => root }).run([
    "--non-interactive", "--dir", root, "--repo", "B:backend", "--dry-run",
  ]);
  assert.equal(result.code, 0);
  assert.match(cap.text(), /dry run/);
  assert.ok(!fs.existsSync(path.join(root, "coord/project.config.js")));
  fs.rmSync(root, { recursive: true, force: true });
});

test("wizard fails loudly when no repos are supplied", () => {
  const root = tmpRoot();
  const cap = capture();
  const result = createCoordInitWizard({ log: cap.log, cwd: () => root }).run([
    "--non-interactive", "--dir", root,
  ]);
  assert.equal(result.code, 1);
  assert.match(cap.text(), /at least one repo/);
  fs.rmSync(root, { recursive: true, force: true });
});

// --- dispatcher wiring -------------------------------------------------------

test("`coord init --wizard` is routed to the wizard by coord-init.run", () => {
  const root = tmpRoot();
  const cap = capture();
  const init = createCoordInit({ log: cap.log, cwd: () => root });
  const result = init.run(["--wizard", "--non-interactive", "--dir", root, "--repo", "B:backend"]);
  assert.equal(result.code, 0);
  assert.match(cap.text(), /coord init --wizard/);
  assert.ok(fs.existsSync(path.join(root, "coord/project.config.js")));
  // The wizard does NOT write the starter board or product stubs (it is a
  // config scaffolder, not the full bootstrap).
  assert.ok(!fs.existsSync(path.join(root, "coord/board/tasks.json")));
  fs.rmSync(root, { recursive: true, force: true });
});
